'use client';

import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { DisclaimerFooter } from '@/components/ui/disclaimer-footer';
import { ChecklistPdf } from '@/components/checklist/checklist-pdf';
import { cn } from '@/lib/utils';
import Link from 'next/link';

interface ArtifactItem {
  id: string;
  category: string;
  title: string;
  description: string | null;
  responsible: string | null;
  estimatedDays: number | null;
  status: string;
  order: number;
}

interface ArtifactViewProps {
  artifactId: string;
  title: string;
  generatedAt: string;
  checklist: Record<string, unknown>;
  items: ArtifactItem[];
}

export function ArtifactView({ title, generatedAt, items }: ArtifactViewProps) {
  const categories = items.reduce(
    (acc, item) => {
      if (!acc[item.category]) acc[item.category] = [];
      acc[item.category].push(item);
      return acc;
    },
    {} as Record<string, ArtifactItem[]>
  );

  return (
    <div className="flex min-h-screen flex-col">
      <header className="border-b border-navy-100 bg-white px-6 py-4">
        <div className="mx-auto flex max-w-4xl items-center justify-between">
          <div>
            <Link
              href="/journey/track"
              className="text-sm text-navy-400 transition-colors hover:text-navy-700"
            >
              ← Back to Tracker
            </Link>
            <h1 className="mt-1 text-xl font-bold text-navy-900">{title}</h1>
            <p className="text-sm text-navy-500">
              Generated {new Date(generatedAt).toLocaleDateString('en-AU')}
            </p>
          </div>
          <ChecklistPdf title={title} items={items} categories={categories} />
        </div>
      </header>

      <main className="flex-1 px-6 py-8">
        <div className="mx-auto max-w-4xl space-y-6">
          <Card>
            <div className="rounded-lg bg-navy-50 px-4 py-2 text-xs text-navy-500">
              This checklist was generated by AI and provides general guidance only. It does not
              constitute financial, legal, or tax advice. Review all items with qualified
              professionals before implementation.
            </div>
          </Card>

          {Object.entries(categories).map(([category, catItems]) => (
            <Card key={category}>
              <h2 className="text-lg font-semibold text-navy-900">{category}</h2>
              <div className="mt-4 divide-y divide-navy-50">
                {catItems.map((item) => (
                  <div key={item.id} className="py-3">
                    <div className="flex items-start justify-between gap-4">
                      <div>
                        <p className="font-medium text-navy-800">{item.title}</p>
                        {item.description && (
                          <p className="mt-1 text-sm text-navy-500">{item.description}</p>
                        )}
                      </div>
                      <div className="shrink-0 text-right">
                        {item.responsible && (
                          <span className="block text-xs text-navy-400">{item.responsible}</span>
                        )}
                        {item.estimatedDays && (
                          <span className="block text-xs text-navy-400">
                            ~{item.estimatedDays} days
                          </span>
                        )}
                        <span
                          className={cn(
                            'mt-1 inline-block rounded-full px-2 py-0.5 text-xs font-medium',
                            item.status === 'COMPLETE'
                              ? 'bg-green-100 text-green-700'
                              : item.status === 'IN_PROGRESS'
                                ? 'bg-blue-100 text-blue-700'
                                : item.status === 'BLOCKED'
                                  ? 'bg-red-100 text-red-700'
                                  : 'bg-navy-100 text-navy-600'
                          )}
                        >
                          {item.status.replace('_', ' ')}
                        </span>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </Card>
          ))}
        </div>
      </main>

      <DisclaimerFooter />
    </div>
  );
}
